apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mysimpleapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: mysimpleapp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mysimpleapp
            port:
              number: 3000
