apiVersion: v1
kind: Service
metadata:
  name: mysimpleapp
  labels:
    app: mysimpleapp
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: mysimpleapp
  type: ClusterIP
